services:
  mysql:
    image: mysql:8.0
    container_name: cosmetic-db-dev
    env_file:
      - ./database-service.env
    ports:
      - 3307:3306
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./cosmetic-store-be/s-data/bfystore.sql.gz:/docker-entrypoint-initdb.d/bfystore.sql.gz

    networks:
      - cosmetic-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    container_name: cosmetic-backend-dev
    working_dir: /app
    env_file:
      - ./backend-service.env
    ports:
      - "8080:8080"
    volumes:
      - ./cosmetic-store-be:/app
      - maven_cache_dev:/root/.m2
    networks:
      - cosmetic-network-dev
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -w '%{http_code}' $${SERVICE_HEALTH_CHECK_URL} | grep -q '^200$'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: node:18-alpine
    container_name: cosmetic-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./cosmetic-store-fe:/app
      - node_modules_cache_dev:/app/node_modules
    networks:
      - cosmetic-network-dev
    depends_on:
      - backend
    restart: unless-stopped
    command: >
      sh -c "
        npm install &&
        npm start
      "
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  mysql_data_dev:
  maven_cache_dev:
  node_modules_cache_dev:

networks:
  cosmetic-network-dev:
    driver: bridge