services:
  mysql:
    image: mysql:8.0
    container_name: cosmetic-db
    env_file:
      - ./database-service.env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - cosmetic-network
    command: >
      sh -c "
      curl -L \"$${MYSQL_DUMP_FILE_URL}\" -o /docker-entrypoint-initdb.d/bfystore.sql.gz &&
      /entrypoint.sh mysqld
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: BACKEND__DOCKER_IMAGE_REPO
    container_name: cosmetic-backend
    env_file:
      - ./backend-service.env
    ports:
      - "8080:8080"
    networks:
      - cosmetic-network
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: FRONTEND__DOCKER_IMAGE_REPO
    container_name: cosmetic-frontend
    ports:
      - 80:80
      - 443:443
    networks:
      - cosmetic-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  cosmetic-network:
    driver: bridge
