events {}
http {
  # Basic settings
  proxy_read_timeout 60s;
  proxy_connect_timeout 5s;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto https;

  # Frontend and Backend routing
  server {
    listen 443 ssl;
    server_name cosmetic.dev;

    ssl_certificate     /etc/nginx/certs/local-cert.pem;
    ssl_certificate_key /etc/nginx/certs/local-key.pem;

    # Backend API routes
    location /api/ {
      proxy_pass http://backend:8080/;
    }

    # Frontend routes (catch-all)
    location / {
      proxy_pass http://frontend:80;
    }
  }
}
